// UI_POS.ts - Consistent positioning constants
export const UI_POS = {
  // ------------------------- BOTTOM BAR ------------------------- //
  //BET TAB
  BET_TAB_Y: 0.5,
  VALUE_BAR_WIDTH: 0.09,
  BET_TAB_X: 0.14,
  BET_TAB_MIN_HEIGHT: 35,
  BET_TAB_MAX_HEIGHT_RATIO: 0.55,

  //WINNINGS TAB
  WINNINGS_TAB_Y: 0.5,
  WINNINGS_TAB_X: 0.5,
  WINNINGS_TAB_WIDTH: 0.15,
  WINNINGS_TAB_MIN_HEIGHT: 40,
  WINNINGS_TAB_MAX_HEIGHT_RATIO: 0.55,

  //SPIN BUTTON
  SPIN_BUTTON_Y: 0.5,
  SPIN_BUTTON_X: 0.90,
  SPIN_BUTTON_WIDTH: 0.14,
  SPIN_BUTTON_MIN_HEIGHT: 55,
  SPIN_BUTTON_MAX_HEIGHT_RATIO: 0.75,

  //AUTO SPIN BUTTON
  AUTO_SPIN_BUTTON_Y: 0.5,
  AUTO_SPIN_BUTTON_X: 0.75,
  AUTO_SPIN_BUTTON_WIDTH: 0.14,
  AUTO_SPIN_BUTTON_MIN_HEIGHT: 38,
  AUTO_SPIN_BUTTON_MAX_HEIGHT_RATIO: 0.45,

  
  // ------------------------- TOP BAR ------------------------- //
  //BALANCE TAB
  BALANCE_TAB_Y: 0.5,
  BALANCE_TAB_X: 0.5,
  BALANCE_TAB_WIDTH: 0.19,
  BALANCE_TAB_MIN_HEIGHT: 40,
  BALANCE_TAB_MAX_HEIGHT_RATIO: 0.65,

  //HOME BUTTON
  HOME_BUTTON_Y: 0.5,
  HOME_BUTTON_X: 0.07,
  HOME_BUTTON_WIDTH: 0.1,
  HOME_BUTTON_MIN_HEIGHT: 40,
  HOME_BUTTON_MAX_HEIGHT_RATIO: 0.65,

  //SETTINGS BUTTON
  SETTINGS_BUTTON_Y: 0.5,
  SETTINGS_BUTTON_X: 0.93,
  SETTINGS_BUTTON_WIDTH: 0.1,
  SETTINGS_BUTTON_MIN_HEIGHT: 40,
  SETTINGS_BUTTON_MAX_HEIGHT_RATIO: 0.65,

  //RULES BUTTON
  RULES_BUTTON_Y: 0.5,
  RULES_BUTTON_X: 0.85,
  RULES_BUTTON_WIDTH: 0.1,
  RULES_BUTTON_MIN_HEIGHT: 40,
  RULES_BUTTON_MAX_HEIGHT_RATIO: 0.65,


  // ------------------------- SETTINGS POPUP ------------------------- //
  // POPUP
  SETTINGS_POPUP_WIDTH: 1,
  SETTINGS_POPUP_HEIGHT: 1,
  SETTINGS_POPUP_TOP_PERCENTAGE: 40,
  SETTINGS_POPUP_HEIGHT_PERCENTAGE : '70%',

  // CLOSE BUTTON
  CLOSE_BUTTON_X: 0.95,
  CLOSE_BUTTON_Y: 0.94,
  CLOSE_BUTTON_WIDTH: 0.1,
  CLOSE_BUTTON_HEIGHT: 0.1,

  // NAVIGATION BUTTONS
  NAVIGATION_BUTTON_X: 0.04,
  NAVIGATION_BUTTON_Y: 0.5,
  NAVIGATION_BUTTON_WIDTH: 0.13,
  NAVIGATION_BUTTON_HEIGHT: 0.13,

  // ----------------------- SETTINGS CONTENT ----------------------- //
  AUDIO_SLIDER_X_RATIO: 0.5,
  AUDIO_SLIDER_Y_RATIO: 0.4,
  AUDIO_SLIDER_WIDTH_RATIO: 0.25,
  AUDIO_SLIDER_HEIGHT_RATIO: 0.02,
  AUDIO_SLIDER_RADIUS_RATIO: 0.03,

  VERTICAL_GAP_BETWEEN_SLIDERS: 0.15,

  AUDIO_BUTTON_X_RATIO: 0.3,
  AUDIO_BUTTON_Y_RATIO: 0.41,
  AUDIO_BUTTON_WIDTH_RATIO: 0.1,
  AUDIO_BUTTON_HEIGHT_RATIO: 0.1,

  // --------------------- RULES CONTENT --------------------- //
  RULES_PAGE_WIDTH_RATIO: 0.7,
  RULES_PAGE_HEIGHT_RATIO: 0.7,
  RULES_PAGE_X_RATIO: 0.5,
  RULES_PAGE_Y_RATIO: 0.5,

  // ------------------------- WIN POPUP ------------------------- //
  WIN_POPUP_X: 0.5,
  WIN_POPUP_Y: 0.5,
  WIN_POPUP_WIDTH: 0.4,
  WIN_POPUP_HEIGHT: 0.6,

  // ------------- REEL COLUMN RATIOS -------------- //
  REEL_CONTAINER_EDGES_SPACING_RATIO: 0.19,
  // export const REEL_COLUMN_WIDTH_RATIO = 0.17;
  REEL_COLUMN_HEIGHT_RATIO: 1,
  REEL_COLUMN_OFFSET_RATIO: -0.007,
  // export const REEL_COLUMN_X_RATIO = 0.2;
  REEL_COLUMN_Y_RATIO: 0.5, 
}