// UI_POS.ts - Consistent positioning constants
export const UI_POS = {

  //BET TAB
  BET_TAB_Y: 0.5,
  VALUE_BAR_WIDTH: 0.06,
  BET_TAB_X: 0.14,
  BET_TAB_MIN_HEIGHT: 35,
  BET_TAB_MAX_HEIGHT_RATIO: 0.4,

  //BALANCE TAB
  BALANCE_TAB_Y: 0.5,
  BALANCE_TAB_X: 0.5,
  BALANCE_TAB_WIDTH: 0.17,
  BALANCE_TAB_MIN_HEIGHT: 35,
  BALANCE_TAB_MAX_HEIGHT_RATIO: 0.45,

  //WINNINGS TAB
  WINNINGS_TAB_Y: 0.5,
  WINNINGS_TAB_X: 0.5,
  WINNINGS_TAB_WIDTH: 0.17,
  WINNINGS_TAB_MIN_HEIGHT: 40,
  WINNINGS_TAB_MAX_HEIGHT_RATIO: 0.45,

  //SPIN BUTTON
  SPIN_BUTTON_Y: 0.5,
  SPIN_BUTTON_X: 0.90,
  SPIN_BUTTON_WIDTH: 0.14,
  SPIN_BUTTON_MIN_HEIGHT: 50,
  SPIN_BUTTON_MAX_HEIGHT_RATIO: 0.45,
}