// UI_POS.ts - Consistent positioning constants
export const UI_POS = {
  // ------------------------- BOTTOM BAR ------------------------- //
  //BET TAB
  BET_TAB_Y: 0.5,
  VALUE_BAR_WIDTH: 0.06,
  BET_TAB_X: 0.14,
  BET_TAB_MIN_HEIGHT: 35,
  BET_TAB_MAX_HEIGHT_RATIO: 0.4,

  //WINNINGS TAB
  WINNINGS_TAB_Y: 0.5,
  WINNINGS_TAB_X: 0.5,
  WINNINGS_TAB_WIDTH: 0.15,
  WINNINGS_TAB_MIN_HEIGHT: 40,
  WINNINGS_TAB_MAX_HEIGHT_RATIO: 0.45,

  //SPIN BUTTON
  SPIN_BUTTON_Y: 0.5,
  SPIN_BUTTON_X: 0.90,
  SPIN_BUTTON_WIDTH: 0.14,
  SPIN_BUTTON_MIN_HEIGHT: 55,
  SPIN_BUTTON_MAX_HEIGHT_RATIO: 0.45,

  //AUTO SPIN BUTTON
  AUTO_SPIN_BUTTON_Y: 0.5,
  AUTO_SPIN_BUTTON_X: 0.75,
  AUTO_SPIN_BUTTON_WIDTH: 0.14,
  AUTO_SPIN_BUTTON_MIN_HEIGHT: 38,
  AUTO_SPIN_BUTTON_MAX_HEIGHT_RATIO: 0.45,

  
  // ------------------------- TOP BAR ------------------------- //
  //BALANCE TAB
  BALANCE_TAB_Y: 0.5,
  BALANCE_TAB_X: 0.5,
  BALANCE_TAB_WIDTH: 0.19,
  BALANCE_TAB_MIN_HEIGHT: 40,
  BALANCE_TAB_MAX_HEIGHT_RATIO: 0.45,

  //HOME BUTTON
  HOME_BUTTON_Y: 0.5,
  HOME_BUTTON_X: 0.07,
  HOME_BUTTON_WIDTH: 0.1,
  HOME_BUTTON_MIN_HEIGHT: 40,
  HOME_BUTTON_MAX_HEIGHT_RATIO: 0.45,

  //SETTINGS BUTTON
  SETTINGS_BUTTON_Y: 0.5,
  SETTINGS_BUTTON_X: 0.93,
  SETTINGS_BUTTON_WIDTH: 0.1,
  SETTINGS_BUTTON_MIN_HEIGHT: 40,
  SETTINGS_BUTTON_MAX_HEIGHT_RATIO: 0.45,

  //RULES BUTTON
  RULES_BUTTON_Y: 0.5,
  RULES_BUTTON_X: 0.87,
  RULES_BUTTON_WIDTH: 0.1,
  RULES_BUTTON_MIN_HEIGHT: 40,
  RULES_BUTTON_MAX_HEIGHT_RATIO: 0.45,


  // ------------------------- SETTINGS POPUP ------------------------- //
  // POPUP
  SETTINGS_POPUP_WIDTH: 1,
  SETTINGS_POPUP_HEIGHT: 1,
  SETTINGS_POPUP_TOP_PERCENTAGE: 40,
  SETTINGS_POPUP_HEIGHT_PERCENTAGE : '70%',

  // CLOSE BUTTON
  CLOSE_BUTTON_X: 0.95,
  CLOSE_BUTTON_Y: 0.94,
  CLOSE_BUTTON_WIDTH: 0.1,
  CLOSE_BUTTON_HEIGHT: 0.1,
}